### ISSUE TITLE
Fix border cases

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#20]
These do not work  at this moment for graph6. Need to check for dgraph6 and sparse6 too. 

```r
> # Graph of size 0
> (g6 <- rawToChar(as.raw(fN(0))))
[1] "?"
> as_adjacency(g6)

 Error in rep(what, l - length(x)) : invalid 'times' argument
 
> 
> # Graph of size 1
> (g6 <- rawToChar(as.raw(fN(1))))
[1] "@"
> as_adjacency(g6)

 Error in rep(what, l - length(x)) : invalid 'times' argument
```

Edit: work is done on `i20-border-cases` branch.

**Comment by schochastics** [comment]
After fixing the boundary cases, some of the tests fail because the output types are different
e.g. line 95-102 in `test-i20-border-cases.R` fails because `igraph_from_sparse6()` returns a list and not an igraph object
![](https://user-images.githubusercontent.com/17147355/149412227-9a57894a-d4aa-4e42-853b-b7fcc0800c46.png)

Would it be ok to change such tests to
```r
expect_true(igraph::identical_graphs(
    igraph_from_sparse6(string)[[1]],
    g0u
  ))
```

**Comment by mbojan** [comment]
> After fixing the boundary cases, some of the tests fail because the output types are different e.g. line 95-102 in `test-i20-border-cases.R` fails because `igraph_from_sparse6()` returns a list and not an igraph object ![](https://user-images.githubusercontent.com/17147355/149412227-9a57894a-d4aa-4e42-853b-b7fcc0800c46.png)
> 
> Would it be ok to change such tests to
> 
> ```r
> expect_true(igraph::identical_graphs(
>     igraph_from_sparse6(string)[[1]],
>     g0u
>   ))
> ```

Yes. I think its best for these functions to always return a list even if dealing with a single string.(much like `strsplit()`).
